    // This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import KeyboardController from "./keyboard_controller"
application.register("keyboard", KeyboardController)

import PlayerReadyController from "./playerReady_controller"
application.register("playerReady", PlayerReadyController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)