    // This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import InputController from "./input_controller"
application.register("input", InputController)

import PlayerReadyController from "./playerReady_controller"
application.register("playerReady", PlayerReadyController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import DisplayController from "./display_controller"
application.register("display", DisplayController)
